// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsdervbhzvpkfvychezw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZGVydmJoenZwa2Z2eWNoZXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTY1MzksImV4cCI6MjA2NDg5MjUzOX0.yBXg5njnHT3Pvs895sFml3bSIBDZiG9pJY84iwE-CfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);